version: "3.8"
services:
    nginx:
        image: auddyhub/mern-nginx:latest
        restart: always
        depends_on:
            - frontend
            - backend
        ports:
            - "80:80"

    frontend:
        image: auddyhub/mern-frontend:latest
        environment:
            - CHOKIDAR_USEPOLLING=true

    backend:
        image: auddyhub/mern-backend:latest
        env_file:
            - ./backend/.env
